### ISSUE TITLE
NSString Fails to compile 

### ISSUE THREAD

**Issue by rmottola** [gnustep/libs-base#459] opened 2024-11-07 20:07 UTC
```
 Compiling file NSString.m ...
NSString.m:879:1: error: method definition not in @implementation context
  879 | {
      | ^
NSString.m:884:1: error: method definition not in @implementation context
  884 | {
      | ^

```

**Comment by fredkiefer** [comment] 2024-11-07 22:29
I think that is caused by a misplaced #endif. Maybe the one on line 875 actually belongs in line 660? This only makes a difference if ICU is not installed. This is the reason why it only affects you and why you will have to check this idea yourself.

Hope this helps.

**Comment by rmottola** [comment] 2024-11-08 00:44
Indeed, this this is a compilation without ICU. Do not attempt that often... this system was out-of-order for some months due to OS upgrade

**Comment by rmottola** [comment] 2024-11-08 00:48
That's why it is good to comment very long ifdef's.... I think you are right, trying out the fix.

**Comment by rfm** [comment] 2024-11-08 10:12
I committed the fix

**Closed** 2024-11-08 10:11 UTC

**Comment by rmottola** [comment] 2024-11-08 16:21
Darn.. I was slow making the PR from the push... and you closed the case meanwhile @rfm :) feel free to merge if you wish or discard.

https://github.com/gnustep/libs-base/pull/460

Mine had some comments.... just to read it better.
