### ISSUE TITLE
CI currently broken on NSURLConnection tests

### ISSUE THREAD

**Issue by ivucica** [gnustep/libs-base#120] opened 2020-04-13 23:46 UTC
It looks like ccb8594bc02fb679c123340e72131ac67fd43e2b has broken the build on CI. At least build starts to fail there, and changes to `NSURLProtocol` might be related to breaking `NSURLConnection` tests.

Perhaps something to do with the use of protocol syntax? All of clang and gcc buids seem to be failing on `NSURLConnection` related tests.

```
base/NSURLConnection/basic.m:
Failed file:     basic.m aborted without running all tests!
base/NSURLConnection/test01.m:
Failed file:     test01.m aborted without running all tests!
base/NSURLConnection/test04.m:
Failed file:     test04.m aborted without running all tests!
base/NSURLConnection/test05.m:
Failed file:     test05.m aborted without running all tests!
```

Unfortunately I cannot see more detailed output.

I suppose it's best to assign to @rfm as this was his push.

**Comment by rfm** [comment] 2020-04-14 07:29
Thanks ... looks like somehow a line was missed from my commit (the regression tests passed for me before I committed), because my code had the retain but the code in the repository did not.
Anyway, that was easy for me to correct.

**Closed by rfm** 2020-04-14 07:29 UTC
