### ISSUE TITLE
Performance improvements in NSOrderedSet

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#51] opened 2019-06-27 06:06 UTC
RFM Commented:  

I have to apologise for taking so very long before I had a chance to look at this issue at all. even now I've really only had a quick look, concentrating on the concrete implementation. I also had a quick skim of the Apple documentation.
One paragraph from the intro of the documentation struck me:

You can use ordered sets as an alternative to arrays when the order of elements is important and performance in testing whether an object is contained in the set is a consideration—testing for membership of an array is slower than testing for membership of a set.

This suggests to me that the current concrete class implementation (based on GSIArray) may be a problematic approach: perhaps the representation should fundamentally be a hash-map to rapid testing of membership, rather than an array for rapid enumeration and access by index (or both data structures could be used to hold the same objects).

If we assume that it's acceptable for access by index to be really slow for very large collections, it would be possible to implement this based on an extended version of GSIMap (or some other hash table implementation), since this contains a linked list of nodes (and of course the linked list would be used to provide ordering and access by index). The modification required would be having an alternative version of the node addition code to maintain the linked list ordering, as well as a version of the code to resize the GSIMap (so it maintains the list ordering).

Alternatively, (simplest code approach giving high performance for both forms of access, but higher memory footprint), I'd use both a GSIMap and a GSIArray and store objects in both. In that case it would make sense to configure one data structure to manage retain/release and the other data structure to refrain from doing retain/release.

**Comment by triplef** [comment] 2019-06-27 07:31
I think this is a duplicate of #47.

**Comment by fredkiefer** [comment] 2019-06-30 18:51
I implemented the mixed approach described and added a few additional performance improvements.

**Closed by fredkiefer** 2019-06-30 18:51 UTC
